# yaml-language-server: $schema=https://www.schemastore.org/prettierrc.json
---
arrowParens: always
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
singleAttributePerLine: false
bracketSameLine: false
jsxSingleQuote: true
printWidth: 120
proseWrap: preserve
quoteProps: consistent
requirePragma: false
semi: true
singleQuote: false # consider true
tabWidth: 2
trailingComma: none
useTabs: false
vueIndentScriptAndStyle: true
embeddedLanguageFormatting: auto
experimentalTernaries: true
experimentalOperatorPosition: end
plugins:
  - prettier-plugin-multiline-arrays # It supports multiline arrays in JSON files instead of putting them on a single line (which is hard to read)
