# yaml-language-server: $schema=https://www.schemastore.org/yamllint.json
# docs: https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
---
extends: default

locale: en_US.UTF-8
rules:
  document-start:
    level: warning
    ignore:
      - .cspell.yml
  line-length: disable
  quoted-strings:
    level: error
    quote-type: double
    required: only-when-needed
  comments: disable
  braces:
    level: warning
    max-spaces-inside: 1
  truthy: disable

ignore-from-file:
  - .gitignore
